# Use root/example as user/password credentials
#https://learning.postman.com/docs/writing-scripts/script-references/test-examples/
version: '3'

services:

  db:
    image: wolffjose/mysqldbsampleapi:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - /tmp/mysql_data:/var/lib/mysql  
    environment:
      MYSQL_ROOT_PASSWORD: root

  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:8080

  springapi:
    image: wolffjose/spring-boot-api:latest
    restart: always
    ports:
      - 5000:5000 
    depends_on:
      - db
